const LANGUAGES = {
  ar: {
    arbtn_langtoggler: "الغة العربيه",
    enbtn_langtoggler: "الغة الانجليزيه",
    home_link: "الرئيسية",
    weare_link: "من نحن",
    features_link: "مميزاتنا",
    contactus_link: "تواصل معنا",
    signasrest_link: "سجل كمطعم",
    introtitle_header: `مرحبا بكم في
        تطبيق <strong>اضمن</strong>`,
    introparagraph_header: `
        هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد
        النص
        العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة
        عدد
        الحروف التى يولدها
        إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما
        تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع
        على
        وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم
        الموقع.
        هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد
        النص
        العربى، حيث يمكنك أن
    `,
    discount_text_1:
      "  خصم 30% على اول 3 اوردرات من خلالنا يلا اطلب اوردرك الان مستنى اى !!",
    discount_text_2: `خصم 30% على اول 3 اوردرات من خلالنا يلا اطلب اوردرك الان مستنى اى !! خصم 30% على اول 3
  اوردرات من خلالنا يلا اطلب اوردرك الان مستنى اى !!`,

    aboutus_title: "من نحن",
    aboutus_paragraph: `هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من
  مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة
  إلى زيادة عدد الحروف التى يولدها
  <br>
  المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية
  لتصميم الموقع.
  هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد
  النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى
  إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما
  تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع
  على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم
  الموقع. إلى زيادة عدد الحروف التى يولدها التطبيق.`,
  },

  en: {
    arbtn_langtoggler: "Arabic",
    enbtn_langtoggler: "English",
    home_link: "Home",
    weare_link: "About Us",
    features_link: "Features",
    contactus_link: "Contact Us",
    signasrest_link: "Sign As Resturant",
    introtitle_header: `Welcome to the application of <strong>EDHMN</strong>`,
    introparagraph_header: `
    This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters it generates if you need a larger number of paragraphs that allow The Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator is useful for website designers in particular, where the client often needs to see a real picture of the site design. This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can
    `,
    discount_text_1:
      "30% discount on the first 3 orders through us. Let's order your order now, waiting for any!!",
    discount_text_2: `30% discount on the first 3 orders through us. Let's order your order now, waiting for any!! 30% off the first 3
      Order through us. Let's order your order now. Wait for any!!`,
    aboutus_title: "About Us",
    aboutus_paragraph: `This text is an example of a text that can be replaced in the same space, this text has been generated from the generator of arabic text, where you can generate such text or many other texts in addition to increasing the number of letters generated by
      sites in particular, where the client often needs to see a real picture of the design of the site. This text is an example of a text that can be replaced in the same space, this text has been generated from the generator of the Arabic text, where you can generate such text or many other texts in addition to if you need a larger number of paragraphs allows you to generate arabic text to increase the number of paragraphs as you want, the text will not seem divided and does not contain linguistic errors, the generator of Arabic text is useful for site designers in particular, where the client needs in many Sometimes he sees a real picture of the design of the site. to increase the number of letters generated by the application.`,
  },
};
